### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Kei-OHKAWA** [guimatheus92/Bot_BombCrypto#3]
I ran the following command : 
`pip install -r Requirements.txt
`
I got the following error: Do you know the cause?

```
Collecting pathlib==1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
```

**Comment by guimatheus92** [comment]
Which version of `python` did you install? You can check running the following code: `python --version`

**Comment by Kei-OHKAWA** [comment]
is there a problem?


`Python 3.10.1
`
is there a problem?

**Comment by guimatheus92** [comment]
Yes, if you take a look at the [README.md](https://github.com/guimatheus92/Bot_BombCrypto/blob/main/README.md) file, you will see that you will need to install `Python 3.9.9` version. So uninstall your current python version and install the correct one. You can also follow the tutorial available on how to install [Python](https://github.com/guimatheus92/Bot_BombCrypto/wiki/How-to-execute-BombCrypto-bot).

**Comment by Kei-OHKAWA** [comment]
Thank you for teaching me. Really. .. ..
I'll try.

**Comment by guimatheus92** [comment]
No worries, let me know if you succeed after that please.

**Comment by Kei-OHKAWA** [comment]
The installation was successful.

But when I run it, it stops.


```
C:\Users\E5540\source\repos\Bot_BombCrypto>python main.py
Traceback (most recent call last):
  File "C:\Users\E5540\source\repos\Bot_BombCrypto\main.py", line 4, in <module>
    import tzlocal
ModuleNotFoundError: No module named 'tzlocal'

```

**Comment by Kei-OHKAWA** [comment]
The installation was successful.

But when I run it, it stops.

```

C:\Users\E5540\source\repos\Bot_BombCrypto>python main.py
Traceback (most recent call last):
  File "C:\Users\E5540\source\repos\Bot_BombCrypto\main.py", line 4, in <module>
    import tzlocal
ModuleNotFoundError: No module named 'tzlocal'

```

**Comment by guimatheus92** [comment]
Generally this message is when the library required was not installed, that's strange because it's in the `requirements.txt` file. So try to install again by running the code: `pip install tzlocal`. Or try to run `pip install -r requirements.txt` again.

**Comment by Kei-OHKAWA** [comment]
I started over from the beginning.

The error has changed.


```

C:\Users\E5540\source\repos\Bot_BombCrypto>python main.py
Traceback (most recent call last):
  File "C:\Users\E5540\source\repos\Bot_BombCrypto\main.py", line 5, in <module>
    from bot import reload_page, connect_wallet, login_metamask, treasure_hunt_game, new_map, skip_error_on_game, refresh_hereoes_positions, send_heroes_to_work, first_start, SetTrigger, how_many_coins
  File "C:\Users\E5540\source\repos\Bot_BombCrypto\bot.py", line 8, in <module>
    from controllers import setup_logger, take_screenshot, read_configurations, send_telegram_pic
  File "C:\Users\E5540\source\repos\Bot_BombCrypto\controllers.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'


```

**Comment by guimatheus92** [comment]
Same thing, when you face the error `ModuleNotFoundError: No module named..` that's because the library required was not installed, that's strange because it's in the `requirements.txt` file. So try to install again by running the code: `pip install requests`. Or try to run `pip install -r requirements.txt` in the prompt again.

**Comment by Kei-OHKAWA** [comment]
`Requirement already satisfied:
`

At the beginning of main.py
#! python3.9
Add,
I double-clicked main.py to start it and it worked.
