### ISSUE TITLE
Pacote pywin32 inexistente para Linux

### ISSUE THREAD

**Issue by mittwz** [guimatheus92/Bot_BombCrypto#5]
Opa, tudo bem?

Notei que você fez algumas alterações e atualizações no código, acompanhada desta atualização do BombCrypto eu me interessei em atualizar já para seus novos códigos, porém, os requerimentos agora exigem um pacote chamado **pywin32**. Por utilizar em uma VPS Linux Ubuntu este pacote não esta disponível, afinal, é um pacote exclusivo para windows.

Como proceder? ainda haverá suporte para Linux?
![image](https://user-images.githubusercontent.com/13211496/155380557-dfba9876-4565-4ea6-b3ac-a95f5f6ba617.png)

**Comment by guimatheus92** [comment]
> Opa, tudo bem?
> 
> Notei que você fez algumas alterações e atualizações no código, acompanhada desta atualização do BombCrypto eu me interessei em atualizar já para seus novos códigos, porém, os requerimentos agora exigem um pacote chamado **pywin32**. Por utilizar em uma VPS Linux Ubuntu este pacote não esta disponível, afinal, é um pacote exclusivo para windows.
> 
> Como proceder? ainda haverá suporte para Linux? ![image](https://user-images.githubusercontent.com/13211496/155380557-dfba9876-4565-4ea6-b3ac-a95f5f6ba617.png)

Opa, tudo ótimo e por ai?

Por eu ter uma função que habilita multicontas através de aplicações abertas no sistema, ele utiliza algumas funções do próprio Windows para realizar esse tipo de tarefa, então infelizmente não funciona para Linux mesmo.
Porém se você conseguir, eu recomendo criar uma máquina virtual com o Windows 10 instalado, que funcionará perfeitamente! Além de poder deixar o seu computador livre pro seu uso.

**Comment by mittwz** [comment]
Perfeito, vou fazer isso agora!
