### ISSUE TITLE
Erro ao iniciar o bot

### ISSUE THREAD

**Issue by wDaark** [guimatheus92/Bot_BombCrypto#6]
![image](https://user-images.githubusercontent.com/52123411/155445790-9340a87b-9d5e-48bf-a81f-e8768c36a4b5.png)

**Comment by guimatheus92** [comment]
> ![image](https://user-images.githubusercontent.com/52123411/155445790-9340a87b-9d5e-48bf-a81f-e8768c36a4b5.png)

Aparentemente você deixou o parâmetro `refresh_heroes_only: True`, muda ele para `refresh_heroes_only: False` por favor.

O erro que deu, foi porque ele não conseguiu obter o nome do seu navegador também. Você está usando o navegador `Brave`?
Aproveita e faça o seguinte teste, abre o navegador `Brave`, crie um novo arquivo chamado `multi.py` e cole o código abaixo:

```
import pandas as pd
from pywinauto import Desktop

# Get all windows opens
windows = Desktop(backend="uia").windows()
window = [w.window_text() for w in windows]

# Create dataframe
df_windows = pd.DataFrame(window, columns =['WebBrowser'])

# Export to csv
df_windows.to_csv('window.csv', index=False
```
Após isso, execute o arquivo `multi.py`! Ele irá salvar um arquivo chamado `window.csv`, pega esse arquivo e me mande por favor.
