### ISSUE TITLE
problem with multiaccount

### ISSUE THREAD

**Issue by rndmtyp** [guimatheus92/Bot_BombCrypto#7]
![Screenshot_3](https://user-images.githubusercontent.com/100447925/155810952-71ec4740-f7cf-4fe6-a7ae-2f789075003e.png)

**Comment by guimatheus92** [comment]
> ![Screenshot_3](https://user-images.githubusercontent.com/100447925/155810952-71ec4740-f7cf-4fe6-a7ae-2f789075003e.png)

You must be in the wrong repo, this is not my bot. The logging messages is different from the one I developed.
