### ISSUE TITLE
Login usuário e senha

### ISSUE THREAD

**Issue by mittwz** [guimatheus92/Bot_BombCrypto#8]
Opa, antes de tudo agradecendo por contribuir com seus códigos. Tem sido muito útil para mim e tenho certeza que para várias outras pessoas.

Eu gostaria de saber se você pretende incluir a atualização de login via usuário e senha no bot, seria bastante útil para mim neste momento.

**Comment by guimatheus92** [comment]
> Opa, antes de tudo agradecendo por contribuir com seus códigos. Tem sido muito útil para mim e tenho certeza que para várias outras pessoas.
> 
> Eu gostaria de saber se você pretende incluir a atualização de login via usuário e senha no bot, seria bastante útil para mim neste momento.

Opa, obrigado por acompanhar meu trabalho tanto aqui quanto no bot do SPG. Percebi que seus comentários são simples e objetivos!

Acabei de lançar uma nova versão [#50](https://github.com/guimatheus92/Bot_BombCrypto/commit/40f66d4ef1d76a7c6926a7a660c9c39a2efd27a2) possibilitando conectar no BombCrypto utilizando o login (usuario e senha) ao invés da Metamask.

Para funcionar, basta trocar o parâmetro `connect_with_login: False` para `connect_with_login: True`, e preencher com seu usuário e senha nos parâmetros `login_username` e `login_password`. Dessa forma, ele deixará de conectar com a Metamask e utilizará apenas o login.
